import { AcademicServiceRow } from '@/types/economy';

export const INITIAL_MARKETPLACE_LISTINGS: AcademicServiceRow[] = [
  // 1. COMIDA & SNACKS
  {
    id: 'food-empanadas-1',
    mentor_id: 'usr-lucia',
    mentor: {
      id: 'usr-lucia',
      student_code: 'U21204910',
      full_name: 'Lucía Morales',
      email: 'lucia.m@utp.edu.pe',
      career: 'Administración y Marketing',
      campus: 'Campus San Juan',
      cycle: 6,
      reputation_score: 180,
      created_at: '',
      updated_at: '',
    },
    title: 'Empanadas Artesanales de Carne y Pollo',
    description: 'Empanadas caseras calientes con masa hojaldrada y ají casero. Entrego en mano en descansos y biblioteca.',
    service_type: 'FOOD_SNACKS',
    category: 'FOOD',
    price_cents: 450, // S/ 4.50
    unit_label: 'por unidad',
    delivery_method: 'CAMPUS_MEET',
    campus_location: 'Biblioteca Torre A - Piso 3 (o Cafetería)',
    whatsapp_phone: '51987654321',
    stock_status: 'AVAILABLE_NOW',
    is_active: true,
    rating_avg: 4.9,
    total_reviews: 28,
    tags: ['Calientes', 'Masa Hojaldrada', 'Ají Casero', 'Snack'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'food-brownies-2',
    mentor_id: 'usr-carlos',
    mentor: {
      id: 'usr-carlos',
      student_code: 'U20309182',
      full_name: 'Carlos Benítez',
      email: 'carlos.b@utp.edu.pe',
      career: 'Ingeniería Industrial',
      campus: 'Campus San Juan',
      cycle: 7,
      reputation_score: 140,
      created_at: '',
      updated_at: '',
    },
    title: 'Brownies Melcochudos con Fudge Casero',
    description: 'Brownies con chocolate bitter al 70%, nueces y extra fudge. Perfectos para recargar energía antes de parciales.',
    service_type: 'FOOD_SNACKS',
    category: 'FOOD',
    price_cents: 350, // S/ 3.50
    unit_label: 'por unidad',
    delivery_method: 'CAMPUS_MEET',
    campus_location: 'Pabellón B - Piso 2 (Mesas de Estudio)',
    whatsapp_phone: '51976543210',
    stock_status: 'AVAILABLE_NOW',
    is_active: true,
    rating_avg: 5.0,
    total_reviews: 42,
    tags: ['Chocolate Bitter', 'Nueces', 'Fudge', 'Postres'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'food-triples-3',
    mentor_id: 'usr-andrea',
    mentor: {
      id: 'usr-andrea',
      student_code: 'U22108472',
      full_name: 'Andrea Palacios',
      email: 'andrea.p@utp.edu.pe',
      career: 'Contabilidad y Finanzas',
      campus: 'Campus San Juan',
      cycle: 5,
      reputation_score: 115,
      created_at: '',
      updated_at: '',
    },
    title: 'Sánguches Triples Clásicos (Pollo, Jamón y Palta)',
    description: 'Triples frescos preparados en la mañana. Pan de molde suave con relleno abundante. Pedidos hasta agotar stock.',
    service_type: 'FOOD_SNACKS',
    category: 'FOOD',
    price_cents: 400, // S/ 4.00
    unit_label: 'por paquete (2u)',
    delivery_method: 'CAMPUS_MEET',
    campus_location: 'Entrada Principal Torre A',
    whatsapp_phone: '51965432109',
    stock_status: 'AVAILABLE_NOW',
    is_active: true,
    rating_avg: 4.8,
    total_reviews: 19,
    tags: ['Fresco', 'Desayuno', 'Almuerzo Rápido'],
    created_at: new Date().toISOString(),
  },

  // 2. ASESORÍAS ACADÉMICAS & CODE REVIEWS
  {
    id: 'acad-spring-1',
    mentor_id: 'usr-joan',
    mentor: {
      id: 'usr-joan',
      student_code: 'U20202020',
      full_name: 'Joan Laurente',
      email: 'joan.l@utp.edu.pe',
      career: 'Ingeniería de Software',
      campus: 'Campus San Juan / Digital',
      cycle: 8,
      reputation_score: 250,
      created_at: '',
      updated_at: '',
    },
    title: 'Mentoría 1 a 1: Spring Boot & JPA para APF1',
    description: 'Asesoría intensiva de 1 hora para resolver dudas de Dependency Injection, DTOs, validaciones y configuración RESTful.',
    service_type: 'TUTORING_1ON1',
    category: 'ACADEMIC',
    course_id: 'Desarrollo Web Integrado',
    price_cents: 1800, // S/ 18.00
    unit_label: 'por hora de asesoría',
    duration_minutes: 60,
    delivery_method: 'VIRTUAL',
    campus_location: 'Google Meet / Discord UTP',
    whatsapp_phone: '51987654321',
    stock_status: 'AVAILABLE_NOW',
    is_active: true,
    rating_avg: 4.95,
    total_reviews: 34,
    tags: ['Spring Boot', 'Java 21', 'JPA', 'APF1'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'acad-cloud-2',
    mentor_id: 'usr-mateo',
    mentor: {
      id: 'usr-mateo',
      student_code: 'U20219842',
      full_name: 'Mateo Quispe',
      email: 'mateo.q@utp.edu.pe',
      career: 'Ingeniería de Sistemas e Informática',
      campus: 'Campus San Juan',
      cycle: 7,
      reputation_score: 145,
      created_at: '',
      updated_at: '',
    },
    title: 'Laboratorio Intensivo: VPC, Subredes y EC2 en AWS',
    description: 'Repaso práctico en consola para la PC1 de Servicios Cloud. Creación de VPC paso a paso y solución de tablas de ruteo.',
    service_type: 'TUTORING_1ON1',
    category: 'ACADEMIC',
    course_id: 'Servicios Cloud',
    price_cents: 2000, // S/ 20.00
    unit_label: 'por sesión de 90 min',
    duration_minutes: 90,
    delivery_method: 'CAMPUS_MEET',
    campus_location: 'Laboratorio Cómputo B-204',
    whatsapp_phone: '51976543210',
    stock_status: 'AVAILABLE_NOW',
    is_active: true,
    rating_avg: 4.9,
    total_reviews: 16,
    tags: ['AWS VPC', 'EC2', 'PC1', 'Cloud'],
    created_at: new Date().toISOString(),
  },

  // 3. SERVICIOS DIGITALES & FREELANCE
  {
    id: 'tech-slides-1',
    mentor_id: 'usr-valeria',
    mentor: {
      id: 'usr-valeria',
      student_code: 'U21304921',
      full_name: 'Valeria Mendoza',
      email: 'valeria.m@utp.edu.pe',
      career: 'Diseño Digital / Software',
      campus: 'Campus Digital',
      cycle: 7,
      reputation_score: 160,
      created_at: '',
      updated_at: '',
    },
    title: 'Diseño de Diapositivas Profesionales en Figma / Canva',
    description: 'Transformo tu borrador o Word en diapositivas minimalistas de alto impacto visual listas para tu sustentación o entrega de avance.',
    service_type: 'DESIGN_SLIDES',
    category: 'TECH_DESIGN',
    price_cents: 1500, // S/ 15.00
    unit_label: 'por presentación (hasta 12 slides)',
    delivery_method: 'VIRTUAL',
    campus_location: 'Entrega en PDF / Enlace editable Figma',
    whatsapp_phone: '51954321098',
    stock_status: 'AVAILABLE_NOW',
    is_active: true,
    rating_avg: 5.0,
    total_reviews: 22,
    tags: ['Figma', 'Canva', 'Sustentaciones', 'UI'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tech-docker-2',
    mentor_id: 'usr-diego',
    mentor: {
      id: 'usr-diego',
      student_code: 'U19308129',
      full_name: 'Diego Fernández',
      email: 'diego.f@utp.edu.pe',
      career: 'Ingeniería de Software',
      campus: 'Campus San Juan',
      cycle: 8,
      reputation_score: 135,
      created_at: '',
      updated_at: '',
    },
    title: 'Instalación y Setup de Docker, WSL2 & Entornos Linux',
    description: 'Dejo tu laptop lista y configurada con Docker Desktop, WSL2 Ubuntu, NodeJS, JDK 21 y VS Code sin errores de compatibilidad.',
    service_type: 'TECH_SETUP',
    category: 'TECH_DESIGN',
    price_cents: 1200, // S/ 12.00
    unit_label: 'por configuración completa',
    delivery_method: 'CAMPUS_MEET',
    campus_location: 'Biblioteca Torre A - Piso 2',
    whatsapp_phone: '51943210987',
    stock_status: 'AVAILABLE_NOW',
    is_active: true,
    rating_avg: 4.85,
    total_reviews: 14,
    tags: ['Docker', 'WSL2', 'Linux', 'Setup Dev'],
    created_at: new Date().toISOString(),
  },

  // 4. MATERIALES & SEGUNDA MANO ACADÉMICA
  {
    id: 'second-calc-1',
    mentor_id: 'usr-rodrigo',
    mentor: {
      id: 'usr-rodrigo',
      student_code: 'U19208192',
      full_name: 'Rodrigo Vega',
      email: 'rodrigo.v@utp.edu.pe',
      career: 'Ingeniería Mecatrónica',
      campus: 'Campus San Juan',
      cycle: 9,
      reputation_score: 95,
      created_at: '',
      updated_at: '',
    },
    title: 'Calculadora Científica Casio fx-570LAX ClassWiz (Seminueva)',
    description: 'Calculadora original en excelente estado estético y 100% operativa. Pantalla nítida, ideal para cálculo, física y estadística.',
    service_type: 'SECOND_HAND',
    category: 'SECOND_HAND',
    price_cents: 4500, // S/ 45.00
    unit_label: 'precio único',
    delivery_method: 'CAMPUS_MEET',
    campus_location: 'Entrada Torre A (Punto de Encuentro)',
    whatsapp_phone: '51932109876',
    stock_status: 'AVAILABLE_NOW',
    is_active: true,
    rating_avg: 5.0,
    total_reviews: 8,
    tags: ['Casio', 'Calculadora', 'ClassWiz', 'Cálculo'],
    created_at: new Date().toISOString(),
  },
];
